### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by krak3n77** [Crsarmv7l/TPMS-Flipper#2]
Hi, would adding Toyota TPMS creation be possible in the near future?

**Comment by Crsarmv7l** [comment]
Toyota uses many different TPMS, one which is the PMV-107J they also use the PMV-c210. PMV-107J is already included. PMV-c210 is almost complete, but I can't quite get the CRC8 to line up correctly.

Maybe in the future.

More will be added as rtl_433 nails down some of the unknowns in other TPMS, as I am working from their C source code.

**Comment by krak3n77** [comment]
Ok, also I can help with signal samples if needed, they decode just fine for me with rtl433. Don't know the exact tpms type though.

**Comment by Crsarmv7l** [comment]
> Ok, also I can help with signal samples if needed, they decode just fine for me with rtl433. Don't know the exact tpms type though.

rtl_433 has plenty of test files for everything it can decode. 

For clarity: A CRC8 is an 9 bit checksum, a sum of all bytes in the signal. If you change part of the signal, you have to change the checksum (crc8) as well because that is the first thing a receiver checks before processing the signal. If the message sum doesn't match the stated CRC, the entire message is discarded by the receiver. 

I would bruteforce it, but that is 2^9 or 512 possibilities which would all have to be dmc encoded then generate a .cu8 which would have a long play time for a single valid signal.

At some point I will take another look at it.

I accept pull requests, and this would be a great way to get more signals knowledge if you were inclined
